name: release-weapon-on-back

on:
  push:
    tags:
      - weapon-on-back-v*

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install, format, lint, build and then zip
        run: |
          npm install
          npm run format
          npm run lint
          npm run build:weapon-on-back
          pushd dist && zip -r weapon-on-back.zip weapon-on-back && popd
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.version.outputs.version }}
          body_path: projects/weapon-on-back/CHANGELOG_CURRENT.md
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/weapon-on-back.zip
          asset_name: weapon-on-back.zip
          asset_content_type: application/zip
